spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=itau
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: SeguroService321
  jpa:
    hibernate:
      ddl-auto: update

