spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=itau
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: SeguroService321
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


